first_name=input('Please enter your first name: ')
last_name=input('Please enter your last name: ')
email=input('Please enter your email address: ')
phone_number=input('Please enter your phone number: ')
job_title=input('Please enter your job title: ')
id_number=input('Please enter your ID number: ')
print()
print(f'{last_name.upper()}, {first_name}')
print(f'{job_title.capitalize()}')
print(f'ID: {id_number}')
print()
print(f'{email.lower()}')
print(phone_number)