child=float(input("What is the price of a child's meal? "))
adult=float(input("What is the price of an adult's meal? "))
childNumber=int(input("How many children are there? "))
adultNumber=int(input("How many adults are there? "))
salesTaxRate=float(input("What is the sales tax rate? "))
print()
subtotal=((child)*(childNumber)+(adult)*(adultNumber))
print(f'Subtotal: ${subtotal: .2f}')

salesTax=((subtotal)*(salesTaxRate/100))
print(f'Sales tax: ${salesTax: .2f}')

total=((subtotal)+(salesTax))
print(f'Total: ${total: .2f}')
print()
payment=float(input("What is the payment amount? "))
change=(payment)-(total)
print(f'Change: ${change: .2f}')