color=input('What is your favorite color? ')
print('Your favorite color is...')
print(color)
color2=input('Why is that your favorite color? ')
print('The reason why that is your favorite color is... ')
print(color2)
print(color + ' is a really good color!')